/**
 * @license
 * Copyright 2022 Google LLC
 *
 * Use of this source code is governed by an MIT-style
 * license that can be found in the LICENSE file or at
 * https://opensource.org/licenses/MIT.
 */

// grpc core status codes
// (https://grpc.github.io/grpc/core/md_doc_statuscodes.html)
export const GRPC_CORE_STATUS_CODES: { [status: string]: number } = {
  OK: 0,
  CANCELLED: 1,
  UNKNOWN: 2,
  INVALID_ARGUMENT: 3,
  DEADLINE_EXCEEDED: 4,
  NOT_FOUND: 5,
  ALREADY_EXISTS: 6,
  PERMISSION_DENIED: 7,
  RESOURCE_EXHAUSTED: 8,
  FAILED_PRECONDITION: 9,
  ABORTED: 10,
  OUT_OF_RANGE: 11,
  UNIMPLEMENTED: 12,
  INTERNAL: 13,
  UNAVAILABLE: 14,
  DATA_LOSS: 15,
  UNAUTHENTICATED: 16,
};

// map core gRPC status codes to HTTP status codes
export const GRPC_TO_HTTP_STATUS_CODES: { [status: number]: number } = {
  0: 200, // OK, OK
  1: 500, // Canceled, Internal Server Error
  2: 500, // Unknown, Internal Server Error
  3: 400, // Invalid Argument, Bad Request
  4: 500, // Deadline Exceeded, Internal Server Error
  5: 404, // Not Found, Not Found
  6: 409, // Already Exists, Conflict
  7: 403, // Permission Denied, Forbidden
  8: 429, // Resource Exhausted, Too Many Requests
  9: 500, // Failed Precondition, Internal Server Error
  10: 500, // Aborted, Internal Server Error
  11: 416, // Out of Range,
  12: 501, // Unimplemented, Not Implemented
  13: 500, // Internal, Internal Server Error
  14: 503, // Unavailable, Service Unavailable
  15: 500, // Data Loss, Internal Server Error
  16: 401, // Unauthenticated, Unauthorized
};

// optimization api status codes
// (https://cloud.google.com/optimization/docs/reference/rpc/google.cloud.optimization.v1#optimizetoursvalidationerror)
export const OPTIMIZATION_VALIDATION_CODES: { [status: number]: string } = {
  0: "UNSPECIFIED",

  10: "VALIDATION_TIMEOUT_ERROR", // Validation couldn't be completed within the deadline.

  12: "REQUEST_OPTIONS_ERROR",
  1201: "REQUEST_OPTIONS_INVALID_SOLVING_MODE",
  1202: "REQUEST_OPTIONS_MAX_VALIDATION_ERRORS_WITHOUT_VALIDATE_ONLY",
  1203: "REQUEST_OPTIONS_INVALID_MAX_VALIDATION_ERRORS",
  1204: "REQUEST_OPTIONS_INVALID_GEODESIC_METERS_PER_SECOND",
  1205: "REQUEST_OPTIONS_GEODESIC_METERS_PER_SECOND_TOO_SMALL",
  1206: "REQUEST_OPTIONS_MISSING_GEODESIC_METERS_PER_SECOND",
  1207: "REQUEST_OPTIONS_POPULATE_PATHFINDER_TRIPS_AND_GEODESIC_DISTANCE",
  1208: "REQUEST_OPTIONS_COST_MODEL_OPTIONS_AND_GEODESIC_DISTANCE",

  20: "INJECTED_SOLUTION_ERROR",
  2000: "INJECTED_SOLUTION_MISSING_LABEL",
  2001: "INJECTED_SOLUTION_DUPLICATE_LABEL",
  2002: "INJECTED_SOLUTION_AMBIGUOUS_INDEX",

  22: "SHIPMENT_MODEL_ERROR",
  2200: "SHIPMENT_MODEL_TOO_LARGE",
  2201: "SHIPMENT_MODEL_TOO_MANY_CAPACITY_TYPES",

  24: "INDEX_ERROR",

  26: "TAG_ERROR",

  28: "TIME_WINDOW_ERROR",
  2800: "TIME_WINDOW_INVALID_START_TIME",
  2801: "TIME_WINDOW_INVALID_END_TIME",
  2802: "TIME_WINDOW_INVALID_SOFT_START_TIME",
  2803: "TIME_WINDOW_INVALID_SOFT_END_TIME",
  2804: "TIME_WINDOW_OUTSIDE_GLOBAL_TIME_WINDOW",
  2805: "TIME_WINDOW_START_TIME_AFTER_END_TIME",
  2806: "TIME_WINDOW_INVALID_COST_PER_HOUR_BEFORE_SOFT_START_TIME",
  2807: "TIME_WINDOW_INVALID_COST_PER_HOUR_AFTER_SOFT_END_TIME",
  2808: "TIME_WINDOW_COST_BEFORE_SOFT_START_TIME_WITHOUT_SOFT_START_TIME",
  2809: "TIME_WINDOW_COST_AFTER_SOFT_END_TIME_WITHOUT_SOFT_END_TIME",
  2810: "TIME_WINDOW_SOFT_START_TIME_WITHOUT_COST_BEFORE_SOFT_START_TIME",
  2811: "TIME_WINDOW_SOFT_END_TIME_WITHOUT_COST_AFTER_SOFT_END_TIME",
  2812: "TIME_WINDOW_OVERLAPPING_ADJACENT_OR_EARLIER_THAN_PREVIOUS",
  2813: "TIME_WINDOW_START_TIME_AFTER_SOFT_START_TIME",
  2814: "TIME_WINDOW_SOFT_START_TIME_AFTER_END_TIME",
  2815: "TIME_WINDOW_START_TIME_AFTER_SOFT_END_TIME",
  2816: "TIME_WINDOW_SOFT_END_TIME_AFTER_END_TIME",
  2817: "TIME_WINDOW_COST_BEFORE_SOFT_START_TIME_SET_AND_MULTIPLE_WINDOWS",
  2818: "TIME_WINDOW_COST_AFTER_SOFT_END_TIME_SET_AND_MULTIPLE_WINDOWS",

  30: "TRANSITION_ATTRIBUTES_ERROR",
  3000: "TRANSITION_ATTRIBUTES_INVALID_COST",
  3001: "TRANSITION_ATTRIBUTES_INVALID_COST_PER_KILOMETER",
  3002: "TRANSITION_ATTRIBUTES_DUPLICATE_TAG_PAIR",
  3003: "TRANSITION_ATTRIBUTES_DISTANCE_LIMIT_MAX_METERS_UNSUPPORTED",
  3004: "TRANSITION_ATTRIBUTES_UNSPECIFIED_SOURCE_TAGS",
  3005: "TRANSITION_ATTRIBUTES_CONFLICTING_SOURCE_TAGS_FIELDS",
  3006: "TRANSITION_ATTRIBUTES_UNSPECIFIED_DESTINATION_TAGS",
  3007: "TRANSITION_ATTRIBUTES_CONFLICTING_DESTINATION_TAGS_FIELDS",
  3008: "TRANSITION_ATTRIBUTES_INVALID_DELAY_DURATION",

  32: "CAPACITY_QUANTITY_ERROR",
  3201: "CAPACITY_QUANTITY_NEGATIVE_VALUE",
  3202: "CAPACITY_QUANTITY_DUPLICATE_TYPE",

  33: "LOAD_LIMIT_ERROR",
  3301: "LOAD_LIMIT_MISSING_TYPE",
  3302: "LOAD_LIMIT_DUPLICATE_TYPE",
  3303: "LOAD_LIMIT_INVALID_COST_ABOVE_SOFT_MAX",
  3304: "LOAD_LIMIT_SOFT_MAX_WITHOUT_COST_ABOVE_SOFT_MAX",
  3305: "LOAD_LIMIT_COST_ABOVE_SOFT_MAX_WITHOUT_SOFT_MAX",
  3306: "LOAD_LIMIT_NEGATIVE_SOFT_MAX",
  3307: "LOAD_LIMIT_MIXED_DEMAND_TYPE",

  34: "INTERVAL_ERROR",
  3401: "INTERVAL_MIN_VALUE_EXCEEDS_MAX_VALUE",
  3402: "INTERVAL_NEGATIVE_MIN_VALUE",
  3403: "INTERVAL_NEGATIVE_MAX_VALUE",
  3404: "INTERVAL_MIN_VALUE_EXCEEDS_CAPACITY",
  3405: "INTERVAL_MAX_VALUE_EXCEEDS_CAPACITY",
  3406: "INTERVAL_DUPLICATE_TYPE",

  36: "DISTANCE_LIMIT_ERROR",
  3601: "DISTANCE_LIMIT_INVALID_COST_AFTER_SOFT_MAX",
  3602: "DISTANCE_LIMIT_SOFT_MAX_WITHOUT_COST_AFTER_SOFT_MAX",
  3603: "DISTANCE_LIMIT_COST_AFTER_SOFT_MAX_WITHOUT_SOFT_MAX",
  3604: "DISTANCE_LIMIT_NEGATIVE_MAX",
  3605: "DISTANCE_LIMIT_NEGATIVE_SOFT_MAX",
  3606: "DISTANCE_LIMIT_SOFT_MAX_LARGER_THAN_MAX",

  38: "DURATION_LIMIT_ERROR",
  3800: "DURATION_LIMIT_NEGATIVE_MAX",
  3801: "DURATION_LIMIT_NEGATIVE_SOFT_MAX",
  3802: "DURATION_LIMIT_INVALID_COST_PER_HOUR_AFTER_SOFT_MAX",
  3803: "DURATION_LIMIT_SOFT_MAX_WITHOUT_COST_AFTER_SOFT_MAX",
  3804: "DURATION_LIMIT_COST_AFTER_SOFT_MAX_WITHOUT_SOFT_MAX",
  3805: "DURATION_LIMIT_NEGATIVE_QUADRATIC_SOFT_MAX",
  3806: "DURATION_LIMIT_INVALID_COST_AFTER_QUADRATIC_SOFT_MAX",
  3807: "DURATION_LIMIT_QUADRATIC_SOFT_MAX_WITHOUT_COST_PER_SQUARE_HOUR",
  3808: "DURATION_LIMIT_COST_PER_SQUARE_HOUR_WITHOUT_QUADRATIC_SOFT_MAX",
  3809: "DURATION_LIMIT_QUADRATIC_SOFT_MAX_WITHOUT_MAX",
  3810: "DURATION_LIMIT_SOFT_MAX_LARGER_THAN_MAX",
  3811: "DURATION_LIMIT_QUADRATIC_SOFT_MAX_LARGER_THAN_MAX",
  3812: "DURATION_LIMIT_DIFF_BETWEEN_MAX_AND_QUADRATIC_SOFT_MAX_TOO_LARGE",

  40: "SHIPMENT_ERROR",

  42: "VEHICLE_ERROR",
  4200: "VEHICLE_EMPTY_REQUIRED_OPERATOR_TYPE",
  4201: "VEHICLE_DUPLICATE_REQUIRED_OPERATOR_TYPE",
  4202: "VEHICLE_NO_OPERATOR_WITH_REQUIRED_OPERATOR_TYPE",
  4203: "VEHICLE_EMPTY_START_TAG",
  4204: "VEHICLE_DUPLICATE_START_TAG",
  4205: "VEHICLE_EMPTY_END_TAG",
  4206: "VEHICLE_DUPLICATE_END_TAG",

  44: "VISIT_REQUEST_ERROR",
  4400: "VISIT_REQUEST_EMPTY_TAG",
  4401: "VISIT_REQUEST_DUPLICATE_TAG",
  4402: "VISIT_REQUEST_EMPTY_VISIT_TYPE",
  4403: "VISIT_REQUEST_DUPLICATE_VISIT_TYPE",

  46: "PRECEDENCE_ERROR",

  48: "BREAK_ERROR",
  4800: "BREAK_RULE_EMPTY",
  4801: "BREAK_REQUEST_UNSPECIFIED_DURATION",
  4802: "BREAK_REQUEST_UNSPECIFIED_EARLIEST_START_TIME",
  4803: "BREAK_REQUEST_UNSPECIFIED_LATEST_START_TIME",
  4804: "BREAK_REQUEST_INVALID_DURATION",
  4805: "BREAK_REQUEST_LATEST_START_TIME_BEFORE_EARLIEST_START_TIME",
  4806: "BREAK_REQUEST_EARLIEST_START_TIME_BEFORE_GLOBAL_START_TIME",
  4807: "BREAK_REQUEST_LATEST_END_TIME_AFTER_GLOBAL_END_TIME",
  4808: "BREAK_REQUEST_OVERLAPPING_ADJACENT_OR_EARLIER_THAN_PREVIOUS",
  4809: "BREAK_INTER_BREAK_DURATION_LIMIT_NEGATIVE_MAXIMUM_ELAPSED_TIME",
  4810: "BREAK_INTER_BREAK_DURATION_LIMIT_INVALID_MINIMUM_DURATION",

  50: "SHIPMENT_TYPE_INCOMPATIBILITY_ERROR",
  5001: "SHIPMENT_TYPE_INCOMPATIBILITY_EMPTY_TYPE",
  5002: "SHIPMENT_TYPE_INCOMPATIBILITY_LESS_THAN_TWO_TYPES",
  5003: "SHIPMENT_TYPE_INCOMPATIBILITY_DUPLICATE_TYPE",
  5004: "SHIPMENT_TYPE_INCOMPATIBILITY_INVALID_INCOMPATIBILITY_MODE",
  5005: "SHIPMENT_TYPE_INCOMPATIBILITY_TOO_MANY_INCOMPATIBILITIES",
  52: "SHIPMENT_TYPE_REQUIREMENT_ERROR",
  52001: "SHIPMENT_TYPE_REQUIREMENT_NO_REQUIRED_TYPE",
  52002: "SHIPMENT_TYPE_REQUIREMENT_NO_DEPENDENT_TYPE",
  52003: "SHIPMENT_TYPE_REQUIREMENT_INVALID_REQUIREMENT_MODE",
  52004: "SHIPMENT_TYPE_REQUIREMENT_TOO_MANY_REQUIREMENTS",
  52005: "SHIPMENT_TYPE_REQUIREMENT_EMPTY_REQUIRED_TYPE",
  52006: "SHIPMENT_TYPE_REQUIREMENT_DUPLICATE_REQUIRED_TYPE",
  52007: "SHIPMENT_TYPE_REQUIREMENT_NO_REQUIRED_TYPE_FOUND",
  52008: "SHIPMENT_TYPE_REQUIREMENT_EMPTY_DEPENDENT_TYPE",
  52009: "SHIPMENT_TYPE_REQUIREMENT_DUPLICATE_DEPENDENT_TYPE",
  52010: "SHIPMENT_TYPE_REQUIREMENT_SELF_DEPENDENT_TYPE",
  52011: "SHIPMENT_TYPE_REQUIREMENT_GRAPH_HAS_CYCLES",

  54: "VEHICLE_OPERATOR_ERROR",
  5400: "VEHICLE_OPERATOR_EMPTY_TYPE",
  5401: "VEHICLE_OPERATOR_MULTIPLE_START_TIME_WINDOWS",
  5402: "VEHICLE_OPERATOR_SOFT_START_TIME_WINDOW",
  5403: "VEHICLE_OPERATOR_MULTIPLE_END_TIME_WINDOWS",
  5404: "VEHICLE_OPERATOR_SOFT_END_TIME_WINDOW",

  9: "RESULT_ERROR",
};
